_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: ETTh2_eval
  offset: 11520
  eval_length: 2880
  prediction_lengths: [96]
  context_lengths: [96]
  patch_sizes: [8, 16, 32]