_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: Exchange_eval
  offset: 6070
  eval_length: 1520
  prediction_lengths: [96]
  context_lengths: [96]
  patch_sizes: [8, 16, 32]