_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: Weather_eval
  offset: 42157
  eval_length: 10540
  prediction_lengths: [96]
  context_lengths: [96]
  patch_sizes: [8, 16, 32]