hydra:
  run:
    dir: /data/Blob_EastUS/v-zhenwzhang/log/moirai_pretrain/${hydra:runtime.choices.model}/${hydra:runtime.choices.data}/${run_name}
defaults:
  - model: ???
  - data: ???
  - val_data: null
  - _self_
run_name: ???
seed: 0
tf32: true
compile: false  # set to mode: default, reduce-overhead, max-autotune
ckpt_path: null  # set to "last" to resume training
trainer:
  _target_: lightning.Trainer
  accelerator: cuda
  devices: 1
  strategy: auto
  num_nodes: 1
  precision: 32
  logger:
      _target_: lightning.pytorch.loggers.TensorBoardLogger
      save_dir: ${hydra:runtime.output_dir}
      name: logs
  # max_epochs: 1_000
  max_epochs: 1
  enable_progress_bar: true
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
train_dataloader:
  _target_: uni2ts.data.loader.DataLoader
  batch_size: 128
  batch_size_factor: 2.0
  cycle: true
  num_batches_per_epoch: 1000
  shuffle: true
  num_workers: 0
  collate_fn:
    _target_: uni2ts.data.loader.PackCollate
    max_length: ${model.module_kwargs.max_seq_len}
    seq_fields: ${cls_getattr:${model._target_},seq_fields}
    pad_func_map: ${cls_getattr:${model._target_},pad_func_map}
  pin_memory: true
  drop_last: true
  fill_last: false
  worker_init_fn: null
  prefetch_factor: 2
  persistent_workers: true