description: moirai small finetune lotsa_v1_weighted all

target:
  service: sing
  name: msrresrchvc

# name: msrresrchvc, msroctovc
# amlt-sing/acpt-2.0.1-py3.10-cuda11.8
# amlt-sing/acpt-2.2.1-py3.10-cuda12.1
environment:
  image: amlt-sing/acpt-2.3.1-py3.10-cuda12.1
  setup:
    - pip install -e .

code:
  # local directory of the code. this will be uploaded to the server.
  local_dir: $CONFIG_DIR/..

storage:
  shared_data:
    storage_account_name: epeastus
    container_name: cov19
    mount_dir: /data/Blob_EastUS

jobs:
- name: moirai_pretrain finetune lotsa_v1_weighted all seed 321
  sku: 80G1-A100
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/e033d461-1923-44a7-872b-78f1d35a86dd/resourcegroups/Shun/providers/Microsoft.ManagedIdentity/userAssignedIdentities/epeastus_mi" 
  command:
  - sh scripts/finetune.sh lotsa_v1_weighted

# search:
#   job_template:
#     name: "{experiment_name:s}_{dataset:s}"
#     sku: 80G1-A100
#     identity: managed
#     command:
#       - sh scripts/finetune.sh {dataset}
#     submit_args:
#       env:
#         _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/e033d461-1923-44a7-872b-78f1d35a86dd/resourcegroups/Shun/providers/Microsoft.ManagedIdentity/userAssignedIdentities/epeastus_mi" 
#   type: grid
#   max_trials: 8
#   params:
#     - name: dataset
#       values: ["lotsa_v1_weighted_group1", "lotsa_v1_weighted_group2", "lotsa_v1_weighted_group3", "lotsa_v1_weighted_group4", "lotsa_v1_weighted_group5"]
